const DATA={
'30-70':{name:'30% BR + 70% MUNDIAL',color:'green',plans:[
{name:'START',followers:'500',likes:'5.000',views:'7.500',posts:5,comments:0,price:'R$ 14,99'},
{name:'BÁSICO',followers:'1.000',likes:'10.000',views:'15.000',posts:7,comments:0,price:'R$ 34,90'},
{name:'PRO',followers:'2.000',likes:'20.000',views:'30.000',posts:10,comments:5,price:'R$ 69,90',hot:1},
{name:'PREMIUM',followers:'5.000',likes:'45.000',views:'75.000',posts:15,comments:10,price:'R$ 159,90'},
{name:'MASTER',followers:'10.000',likes:'100.000',views:'150.000',posts:20,comments:20,price:'R$ 329,90'}]},
'50-50':{name:'50% BR + 50% MUNDIAL',color:'yellow',plans:[
{name:'START',followers:'500',likes:'5.000',views:'7.500',posts:5,comments:0,price:'R$ 19,90'},
{name:'BÁSICO',followers:'1.000',likes:'10.000',views:'15.000',posts:7,comments:0,price:'R$ 39,90'},
{name:'PRO',followers:'2.000',likes:'20.000',views:'30.000',posts:10,comments:5,price:'R$ 79,90',hot:1},
{name:'PREMIUM',followers:'5.000',likes:'45.000',views:'75.000',posts:15,comments:10,price:'R$ 179,90'},
{name:'MASTER',followers:'10.000',likes:'100.000',views:'150.000',posts:20,comments:20,price:'R$ 349,90'}]},
br:{name:'100% BRASILEIROS',color:'purple',plans:[
{name:'START',followers:'500',likes:'5.000',views:'7.500',posts:5,comments:0,price:'R$ 89,90'},
{name:'BÁSICO',followers:'1.000',likes:'10.000',views:'15.000',posts:7,comments:0,price:'R$ 149,90'},
{name:'PRO',followers:'2.000',likes:'20.000',views:'30.000',posts:10,comments:5,price:'R$ 249,90',hot:1},
{name:'PREMIUM',followers:'5.000',likes:'45.000',views:'75.000',posts:15,comments:10,price:'R$ 449,90'},
{name:'MASTER',followers:'10.000',likes:'100.000',views:'150.000',posts:20,comments:20,price:'R$ 799,90'}]}};
function num(s){return Number(String(s).replaceAll('.',''))}
function per(total,posts){return Math.floor(num(total)/posts).toLocaleString('pt-BR')}
function startTimer(){const key='midia_offer_until';let end=Number(localStorage.getItem(key));if(!end||end<Date.now()){end=Date.now()+10*60*1000;localStorage.setItem(key,String(end))}const els=document.querySelectorAll('#timer');const tick=()=>{let left=Math.max(0,end-Date.now());let sec=Math.floor(left/1000),m=Math.floor(sec/60),s=sec%60;els.forEach(e=>e.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'));};tick();setInterval(tick,1000)}startTimer();
const key=new URLSearchParams(location.search).get('servico')||sessionStorage.getItem('servico')||'30-70';const svc=DATA[key]||DATA['30-70'];
if(document.querySelector('#plans')){
 sessionStorage.setItem('servico',key);document.querySelector('#service').textContent=svc.name;
 document.querySelector('#plans').innerHTML=svc.plans.map((p,i)=>{const lp=per(p.likes,p.posts),vp=per(p.views,p.posts);return `<article class="plan-card ${svc.color} ${p.hot?'featured':''}" data-index="${i}">${p.hot?'<span class="tag">🔥 MAIS VENDIDO</span>':''}<div class="plan-top"><div><span class="plan-kicker">🚀 PACOTE DE ENGAJAMENTO</span><h3>${p.name}</h3></div><strong>${p.price}</strong></div><div class="benefit-grid"><div class="benefit">👤<b>${p.followers}</b><small>seguidores</small></div><div class="benefit">❤️<b>${p.likes}</b><small>curtidas</small></div><div class="benefit">👁️<b>${p.views}</b><small>visualizações</small></div><div class="benefit">📲<b>${p.posts}</b><small>publicações</small></div>${p.comments?`<div class="benefit">💬<b>${p.comments}</b><small>comentários</small></div>`:''}</div><div class="distribution"><b>📲 Você recebe um pacote completo</b><div>❤️ ${p.likes} curtidas para distribuir</div><div>👁️ ${p.views} visualizações para distribuir</div>${p.comments?`<div>💬 ${p.comments} comentários personalizados</div>`:''}<small>Você escolhe em quais publicações distribuir o engajamento, conforme as condições do pacote.</small></div><button class="plan-cta">QUERO ESTE PACOTE <span>→</span></button></article>`}).join('');
 document.querySelectorAll('.plan-card').forEach(c=>c.addEventListener('click',()=>{const i=Number(c.dataset.index),p=svc.plans[i];sessionStorage.setItem('pedido',JSON.stringify({service:svc.name,plan:p,key}));if(typeof fbq==='function')fbq('track','InitiateCheckout',{content_name:p.name,content_category:svc.name,value:Number(p.price.replace('R$ ','').replace('.','').replace(',','.')),currency:'BRL'});location.href='checkout.html'}));
}
if(document.querySelector('#checkoutCard')){
 const o=JSON.parse(sessionStorage.getItem('pedido')||'null');if(!o){location.href='index.html'}else{
 const p=o.plan,lp=per(p.likes,p.posts),vp=per(p.views,p.posts);
 document.querySelector('#checkoutCard').innerHTML=`<div class="selected"><div><span>🚀 PACOTE SELECIONADO</span><h2>${p.name}</h2><p>${o.service}</p></div><strong>${p.price}</strong><div class="selected-grid"><div>👤 <b>${p.followers}</b><small>seguidores</small></div><div>❤️ <b>${p.likes}</b><small>curtidas</small></div><div>👁️ <b>${p.views}</b><small>visualizações</small></div><div>📲 <b>${p.posts}</b><small>publicações</small></div>${p.comments?`<div>💬 <b>${p.comments}</b><small>comentários</small></div>`:''}</div><div class="distribution">❤️ <b>${lp}</b> curtidas por publicação em média<br>👁️ <b>${vp}</b> visualizações por publicação em média</div></div><form id="orderForm"><div class="form-section"><h3>👤 Seus dados</h3><label>Seu nome<input id="nome" autocomplete="name" placeholder="Digite seu nome" required></label><label>Seu WhatsApp<input id="telefone" inputmode="tel" autocomplete="tel" placeholder="(21) 99999-9999" required></label><label>Seu Instagram<input id="instagram" placeholder="@seuusuario ou link do perfil" required><small>Digite seu <b>@</b> ou cole o <b>link do perfil</b>. Não informe sua senha.</small></label></div><div class="form-section"><h3>💳 Forma de pagamento</h3><div class="pay-grid"><button type="button" class="pay-option" data-pay="Pix">⚡ <b>Pix</b><small>Mais rápido</small></button><button type="button" class="pay-option" data-pay="Cartão">💳 <b>Cartão</b><small>Crédito / débito</small></button></div><input type="hidden" id="pagamento"></div><button class="final-btn" id="finalBtn" type="submit" disabled>💬 FINALIZAR PEDIDO NO WHATSAPP <span>→</span></button><div class="form-trust">🔒 Seus dados estão protegidos　•　🔄 Reposição conforme o pacote　•　💬 Atendimento via WhatsApp</div></form><section class="checkout-proof"><div class="mini-seal">★<b>7 DIAS</b></div><div><b>Compra protegida</b><p>Reposição conforme o pacote e política de devolução em caso de não entrega.</p></div></section>`;
 document.querySelectorAll('.pay-option').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.pay-option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');document.querySelector('#pagamento').value=btn.dataset.pay;validate()}));
 const fields=['nome','telefone','instagram'];fields.forEach(id=>document.querySelector('#'+id).addEventListener('input',validate));
 function validate(){const ok=fields.every(id=>document.querySelector('#'+id).value.trim())&&document.querySelector('#pagamento').value;document.querySelector('#finalBtn').disabled=!ok;document.querySelector('#finalBtn').classList.toggle('ready',!!ok)}
 document.querySelector('#orderForm').addEventListener('submit',e=>{e.preventDefault();const nome=document.querySelector('#nome').value.trim(),telefone=document.querySelector('#telefone').value.trim(),instagram=document.querySelector('#instagram').value.trim(),pag=document.querySelector('#pagamento').value; if(typeof fbq==='function')fbq('track','Lead',{content_name:p.name,content_category:o.service,value:num(p.price),currency:'BRL'});const msg=`🚀 *NOVO PEDIDO — MIDIANET GROWTH*\n\n👤 *Nome:* ${nome}\n📱 *WhatsApp:* ${telefone}\n📸 *Instagram:* ${instagram}\n\n📦 *PACOTE:* ${p.name}\n🌎 *Público:* ${o.service}\n👥 *Seguidores:* ${p.followers}\n❤️ *Curtidas:* ${p.likes}\n👁️ *Visualizações:* ${p.views}\n📲 *Publicações:* ${p.posts}${p.comments?`\n💬 *Comentários personalizados:* ${p.comments}`:''}\n💳 *Pagamento:* ${pag}\n💰 *Valor:* ${p.price}\n\n✅ Quero finalizar meu pedido.`;window.location.href='https://wa.me/5521991689838?text='+encodeURIComponent(msg)});
 }
}

// V7: fallback visual for testimonial photos until real authorized images are added.
document.querySelectorAll('.testi-img').forEach((img, i) => { img.addEventListener('error', () => { img.removeAttribute('src'); img.alt='Foto do cliente'; img.style.objectFit='cover'; img.style.background='linear-gradient(135deg,#4b1d68,#102116)'; }); });
